### ISSUE TITLE
Bug: Update Server Down When its not

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#38]
Error On Update Server

OS: Windows

to recreate: open falix desktop app
![Screenshot (29)](https://user-images.githubusercontent.com/82530339/191383930-1f0ef2f8-c8fa-43b8-b42e-0e93ffe4f055.png)

**Comment by KorbsStudio** [comment]
Since you've mentioned that you're using the MS version, it should ALWAYS skip the update check and the update modal has been completely disabled for the MS version last time I checked.

The reason for disabling the builtin auto update module is because `electron-updater` will always fail when loaded as a UWP application(Microsoft Store App). I guess Microsoft wants people to update from the Microsoft Store Update page only or it is a general issue with `electron-updater`.

I''ll get around to pushing a new update to the Microsoft Store tonight and someone from Microsoft will hopefully approve the update by tomorrow afternoon.

**Comment by AgentDeath253** [comment]
ill close this
